version: '3.9'

services:
  web:
    build: .
    container_name: credit_approval_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/credit_approval
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:15
    container_name: credit_approval_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: credit_approval
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: credit_approval_redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: credit_approval_celery
    command: celery -A credit_approval.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/credit_approval
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  celery-beat:
    build: .
    container_name: credit_approval_celery_beat
    command: celery -A credit_approval.celery_app beat --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/credit_approval
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

volumes:
  postgres_data:
