# Generated by Django 5.1.3 on 2024-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
